### ISSUE TITLE
Error when trying to use StreamingServiceSetCommand

### ISSUE THREAD

**Issue by imorrish** [LibAtem/LibAtem#9]
Not using this class any differently than all the others that use MaskFlags. Happens regardless of which value I try and set.

An error has occurred that was not properly handled. Additional information is shown below. The PowerShell process will exit.
Unhandled exception. PS C:\Users\imorrish\Documents\GitHub\ATEMModule> System.NullReferenceException: Object reference not set to an instance of an object.
   at LibAtem.Serialization.UInt32ListAttribute.Serialize(Boolean reverseBytes, Byte[] data, UInt32 start, Object val) in C:\Users\imorrish\Documents\GitHub\LibAtem\LibAtem\Serialization\UInt32ListAttribute.cs:line 26
   at LibAtem.Serialization.AutoSerializeBase.Serialize(ByteArrayBuilder cmd) in C:\Users\imorrish\Documents\GitHub\LibAtem\LibAtem\Serialization\AutoSerializeBase.cs:line 119
   at LibAtem.Commands.CommandExtensions.ToByteArray(ICommand cmd) in C:\Users\imorrish\Documents\GitHub\LibAtem\LibAtem\Commands\ICommand.cs:line 65
   at LibAtem.Net.AtemClientConnection.CompileNextMessage() in C:\Users\imorrish\Documents\GitHub\LibAtem\LibAtem\Net\AtemClientConnection.cs:line 41
   at LibAtem.Net.AtemConnection.ChooseMsg() in C:\Users\imorrish\Documents\GitHub\LibAtem\LibAtem\Net\AtemConnection.cs:line 348
   at LibAtem.Net.AtemConnection.TrySendQueued(Socket socket) in C:\Users\imorrish\Documents\GitHub\LibAtem\LibAtem\Net\AtemConnection.cs:line 289
   at LibAtem.Net.AtemClient.<StartSendingTimer>b__34_0(Object o) in C:\Users\imorrish\Documents\GitHub\LibAtem\LibAtem\Net\AtemClient.cs:line 133
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ThreadHelper.ThreadStart(Object obj)

**Comment by Julusian** [comment]
The serialization logic wasn't considering null values. This is fixed in 6ea4c7bd9d299e901155c37d2f11d52969b425c9
